//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace QE.CMS.Entities
{

	/// <summary>
	/// 在线客服问题分类
	/// </summary>

	public partial class QuestionCategory
	{

		/// <summary>
		/// 分类Id
		/// </summary>
		public long Id { get; set; }

		/// <summary>
		/// 父节点ID
		/// </summary>
		public long Pid { get; set; }

		/// <summary>
		/// 分类名称
		/// </summary>
		public string CategoryName { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		public long CreateTime { get; set; }

		/// <summary>
		/// 状态
		/// </summary>
		public short Status { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		public long? UpdateTime { get; set; }

		/// <summary>
		/// 浏览量
		/// </summary>
		public long ViewCount { get; set; }

	}

}
